In [6]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [7]:
import os

os.environ["KHISTO_BIN_DIR"] = (
    "/home/elouen/python/khisto-python/src/khiops/build/linux-gcc-debug/bin/khisto"
)
from khisto import histogram, histogram_df, cumulative_distribution_df

In [8]:
import random
import numpy as np

x = np.array([random.gauss(0, 1) for _ in range(1000)])

In [9]:
histogram(x)

(array([0.00731429, 0.04228571, 0.1392    , 0.266     , 0.354     ,
        0.20933333, 0.052     , 0.01828571]),
 array([-3.171875, -2.625   , -1.75    , -1.125   , -0.625   ,  0.875   ,
         1.625   ,  2.375   ,  3.03125 ]))

In [10]:
import jax

x = jax.numpy.array([random.gauss(0, 1) for _ in range(1000)])

In [11]:
histogram(x)

(Array([0.00266667, 0.036     , 0.1216    , 0.2704    , 0.37745455,
        0.192     , 0.084     , 0.00847059], dtype=float32),
 Array([-3.125 , -2.375 , -1.875 , -1.25  , -0.625 ,  0.75  ,  1.5   ,
         2.25  ,  3.3125], dtype=float32))

In [12]:
histogram(x.tolist())

([0.002666666667,
  0.036,
  0.1216,
  0.2704,
  0.3774545455,
  0.192,
  0.084,
  0.008470588235],
 [-3.125, -2.375, -1.875, -1.25, -0.625, 0.75, 1.5, 2.25, 3.3125])

In [13]:
import pandas as pd

x = pd.Series([random.gauss(0, 1) for _ in range(1000)])
histogram(x)

(<pyarrow.lib.DoubleArray object at 0x75ec3d7d5c00>
 [
   0.02317241379,
   0.07466666667,
   0.2016,
   0.3605714286,
   0.176,
   0.0544,
   0.007111111111
 ],
 <pyarrow.lib.DoubleArray object at 0x75ec3d7d5ba0>
 [
   -3.09375,
   -2.1875,
   -1.4375,
   -0.8125,
   0.9375,
   1.5625,
   2.5,
   3.203125
 ])

In [14]:
import polars as pl

x = pl.Series("x", [random.gauss(0, 1) for _ in range(1000)])
histogram(x)

(<pyarrow.lib.DoubleArray object at 0x75ec332b6740>
 [
   0.01391304348,
   0.102,
   0.249,
   0.383,
   0.282,
   0.174,
   0.094,
   0.046,
   0.005565217391
 ],
 <pyarrow.lib.DoubleArray object at 0x75ec332b66e0>
 [
   -3.078125,
   -2,
   -1.5,
   -0.5,
   0.5,
   1,
   1.5,
   2,
   2.5,
   3.21875
 ])

In [15]:
histogram_df(x).to_native()

shape: (18, 9)
┌────────────┬────────────┬──────────┬───────────┬───┬──────────┬────────────┬─────────┬───────────┐
│ lower_boun ┆ upper_boun ┆ length   ┆ frequency ┆ … ┆ density  ┆ granularit ┆ is_best ┆ center    │
│ d          ┆ d          ┆ ---      ┆ ---       ┆   ┆ ---      ┆ y          ┆ ---     ┆ ---       │
│ ---        ┆ ---        ┆ f64      ┆ i64       ┆   ┆ f64      ┆ ---        ┆ bool    ┆ f64       │
│ f64        ┆ f64        ┆          ┆           ┆   ┆          ┆ i32        ┆         ┆           │
╞════════════╪════════════╪══════════╪═══════════╪═══╪══════════╪════════════╪═════════╪═══════════╡
│ -3.078125  ┆ -2.0       ┆ 1.078125 ┆ 15        ┆ … ┆ 0.013913 ┆ 3          ┆ true    ┆ -2.539062 │
│ -2.0       ┆ -1.5       ┆ 0.5      ┆ 51        ┆ … ┆ 0.102    ┆ 3          ┆ true    ┆ -1.75     │
│ -1.5       ┆ -0.5       ┆ 1.0      ┆ 249       ┆ … ┆ 0.249    ┆ 3          ┆ true    ┆ -1.0      │
│ -0.5       ┆ 0.5        ┆ 1.0      ┆ 383       ┆ … ┆ 0.383    ┆ 3          ┆ true    ┆ 0.0       │
│ 0.5        ┆ 1.0        ┆ 0.5      ┆ 141       ┆ … ┆ 0.282    ┆ 3          ┆ true    ┆ 0.75      │
│ …          ┆ …          ┆ …        ┆ …         ┆ … ┆ …        ┆ …          ┆ …       ┆ …         │
│ -3.078125  ┆ -2.0       ┆ 1.078125 ┆ 15        ┆ … ┆ 0.013913 ┆ 2          ┆ false   ┆ -2.539062 │
│ -2.0       ┆ -1.0       ┆ 1.0      ┆ 161       ┆ … ┆ 0.161    ┆ 2          ┆ false   ┆ -1.5      │
│ -1.0       ┆ 1.0        ┆ 2.0      ┆ 663       ┆ … ┆ 0.3315   ┆ 2          ┆ false   ┆ 0.0       │
│ 1.0        ┆ 2.0        ┆ 1.0      ┆ 134       ┆ … ┆ 0.134    ┆ 2          ┆ false   ┆ 1.5       │
│ 2.0        ┆ 3.21875    ┆ 1.21875  ┆ 27        ┆ … ┆ 0.022154 ┆ 2          ┆ false   ┆ 2.609375  │
└────────────┴────────────┴──────────┴───────────┴───┴──────────┴────────────┴─────────┴───────────┘

In [16]:
cum_df = cumulative_distribution_df(x).to_native()
cum_df

shape: (22, 4)
┌───────────┬─────────────┬─────────┬────────────────────────┐
│ position  ┆ granularity ┆ is_best ┆ cumulative_probability │
│ ---       ┆ ---         ┆ ---     ┆ ---                    │
│ f64       ┆ i32         ┆ bool    ┆ f64                    │
╞═══════════╪═════════════╪═════════╪════════════════════════╡
│ -3.078125 ┆ 0           ┆ false   ┆ 0.0                    │
│ 3.21875   ┆ 0           ┆ false   ┆ 1.0                    │
│ -3.078125 ┆ 1           ┆ false   ┆ 0.0                    │
│ -2.0      ┆ 1           ┆ false   ┆ 0.015                  │
│ 2.0       ┆ 1           ┆ false   ┆ 0.973                  │
│ …         ┆ …           ┆ …       ┆ …                      │
│ 1.0       ┆ 3           ┆ true    ┆ 0.839                  │
│ 1.5       ┆ 3           ┆ true    ┆ 0.926                  │
│ 2.0       ┆ 3           ┆ true    ┆ 0.973                  │
│ 2.5       ┆ 3           ┆ true    ┆ 0.996                  │
│ 3.21875   ┆ 3           ┆ true    ┆ 1.0                    │
└───────────┴─────────────┴─────────┴────────────────────────┘

In [17]:
cum_df.filter(pl.col("granularity") == 0)

shape: (2, 4)
┌───────────┬─────────────┬─────────┬────────────────────────┐
│ position  ┆ granularity ┆ is_best ┆ cumulative_probability │
│ ---       ┆ ---         ┆ ---     ┆ ---                    │
│ f64       ┆ i32         ┆ bool    ┆ f64                    │
╞═══════════╪═════════════╪═════════╪════════════════════════╡
│ -3.078125 ┆ 0           ┆ false   ┆ 0.0                    │
│ 3.21875   ┆ 0           ┆ false   ┆ 1.0                    │
└───────────┴─────────────┴─────────┴────────────────────────┘

In [18]:
cumulative_distribution_df([1.0, 2.0, 3.0, 4.0, 5.0], granularity="best").to_native()

pyarrow.Table
position: double
granularity: int32
is_best: bool
cumulative_probability: double
----
position: [[0.5,8]]
granularity: [[0,0]]
is_best: [[true,true]]
cumulative_probability: [[0,1]]