In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os

os.environ["KHISTO_BIN_DIR"] = (
    "/home/elouen/python/khisto-python/src/khiops/build/linux-gcc-debug/bin/khisto"
)
from khisto import histogram, histogram_table, ecdf_values_table

In [3]:
import random
import numpy as np

x = np.array([random.gauss(0, 1) for _ in range(1000)])

In [4]:
histogram(x)

(array([0.00685714, 0.06533333, 0.1984    , 0.36228571, 0.1936    ,
        0.0768    , 0.01032258]),
 array([-3.5625  , -2.25    , -1.5     , -0.875   ,  0.875   ,  1.5     ,
         2.125   ,  3.578125]))

In [5]:
import jax

x = jax.numpy.array([random.gauss(0, 1) for _ in range(1000)])

INFO:2025-12-12 12:28:22,755:jax._src.xla_bridge:808: Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
INFO:jax._src.xla_bridge:Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
WARNING:2025-12-12 12:28:22,758:jax._src.xla_bridge:850: An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.
WARNING:jax._src.xla_bridge:An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

In [6]:
histogram(x)

(Array([0.00444444, 0.034     , 0.084     , 0.26533332, 0.38333333,
        0.15      , 0.076     , 0.03066667, 0.00463768], dtype=float32),
 Array([-3.625   , -2.5     , -2.      , -1.25    , -0.5     ,  1.      ,
         1.5     ,  2.      ,  2.75    ,  3.828125], dtype=float32))

In [7]:
histogram(x.tolist())

([0.004444444444,
  0.034,
  0.084,
  0.2653333333,
  0.3833333333,
  0.15,
  0.076,
  0.03066666667,
  0.004637681159],
 [-3.625, -2.5, -2.0, -1.25, -0.5, 1.0, 1.5, 2.0, 2.75, 3.828125])

In [8]:
import pandas as pd

x = pd.Series([random.gauss(0, 1) for _ in range(1000)])
histogram(x)

(<pyarrow.lib.DoubleArray object at 0x7e7ce8730400>
 [
   0.005209302326,
   0.068,
   0.22912,
   0.3853617021,
   0.2221176471,
   0.0704,
   0.001882352941
 ],
 <pyarrow.lib.DoubleArray object at 0x7e7ce8730640>
 [
   -3.625,
   -2.28125,
   -1.53125,
   -0.75,
   0.71875,
   1.25,
   2.34375,
   3.40625
 ])

In [9]:
import polars as pl

x = pl.Series("x", [random.gauss(0, 1) for _ in range(1000)])
histogram(x, granularity=None)

[(<pyarrow.lib.DoubleArray object at 0x7e7c84720a00>
  [
    0.1649484536
  ],
  <pyarrow.lib.DoubleArray object at 0x7e7c84720be0>
  [
    -2.953125,
    3.109375
  ]),
 (<pyarrow.lib.DoubleArray object at 0x7e7c84721360>
  [
    0.02727868852,
    0.2385,
    0.01802816901
  ],
  <pyarrow.lib.DoubleArray object at 0x7e7c9c1c3dc0>
  [
    -2.953125,
    -2,
    2,
    3.109375
  ]),
 (<pyarrow.lib.DoubleArray object at 0x7e7c847210c0>
  [
    0.02727868852,
    0.145,
    0.33,
    0.149,
    0.01802816901
  ],
  <pyarrow.lib.DoubleArray object at 0x7e7c847213c0>
  [
    -2.953125,
    -2,
    -1,
    1,
    2,
    3.109375
  ]),
 (<pyarrow.lib.DoubleArray object at 0x7e7c84721480>
  [
    0.02727868852,
    0.092,
    0.198,
    0.3493333333,
    0.272,
    0.192,
    0.106,
    0.01802816901
  ],
  <pyarrow.lib.DoubleArray object at 0x7e7c84721420>
  [
    -2.953125,
    -2,
    -1.5,
    -1,
    0.5,
    1,
    1.5,
    2,
    3.109375
  ]),
 (<pyarrow.lib.DoubleArray object at 0x7e7c847214e0>
  [
    0.02727868852,
    0.092,
    0.224,
    0.364,
    0.2626666667,
    0.144,
    0.064,
    0.01802816901
  ],
  <pyarrow.lib.DoubleArray object at 0x7e7c84721600>
  [
    -2.953125,
    -2,
    -1.5,
    -0.75,
    0.5,
    1.25,
    1.75,
    2,
    3.109375
  ])]

In [10]:
histogram_table(x).to_native()

shape: (25, 9)
┌────────────┬────────────┬──────────┬───────────┬───┬──────────┬────────────┬─────────┬───────────┐
│ lower_boun ┆ upper_boun ┆ length   ┆ frequency ┆ … ┆ density  ┆ granularit ┆ is_best ┆ center    │
│ d          ┆ d          ┆ ---      ┆ ---       ┆   ┆ ---      ┆ y          ┆ ---     ┆ ---       │
│ ---        ┆ ---        ┆ f64      ┆ i64       ┆   ┆ f64      ┆ ---        ┆ bool    ┆ f64       │
│ f64        ┆ f64        ┆          ┆           ┆   ┆          ┆ i32        ┆         ┆           │
╞════════════╪════════════╪══════════╪═══════════╪═══╪══════════╪════════════╪═════════╪═══════════╡
│ -2.953125  ┆ -2.0       ┆ 0.953125 ┆ 26        ┆ … ┆ 0.027279 ┆ 3          ┆ false   ┆ -2.476562 │
│ -2.0       ┆ -1.5       ┆ 0.5      ┆ 46        ┆ … ┆ 0.092    ┆ 3          ┆ false   ┆ -1.75     │
│ -1.5       ┆ -1.0       ┆ 0.5      ┆ 99        ┆ … ┆ 0.198    ┆ 3          ┆ false   ┆ -1.25     │
│ -1.0       ┆ 0.5        ┆ 1.5      ┆ 524       ┆ … ┆ 0.349333 ┆ 3          ┆ false   ┆ -0.25     │
│ 0.5        ┆ 1.0        ┆ 0.5      ┆ 136       ┆ … ┆ 0.272    ┆ 3          ┆ false   ┆ 0.75      │
│ …          ┆ …          ┆ …        ┆ …         ┆ … ┆ …        ┆ …          ┆ …       ┆ …         │
│ -2.953125  ┆ -2.0       ┆ 0.953125 ┆ 26        ┆ … ┆ 0.027279 ┆ 2          ┆ false   ┆ -2.476562 │
│ -2.0       ┆ -1.0       ┆ 1.0      ┆ 145       ┆ … ┆ 0.145    ┆ 2          ┆ false   ┆ -1.5      │
│ -1.0       ┆ 1.0        ┆ 2.0      ┆ 660       ┆ … ┆ 0.33     ┆ 2          ┆ false   ┆ 0.0       │
│ 1.0        ┆ 2.0        ┆ 1.0      ┆ 149       ┆ … ┆ 0.149    ┆ 2          ┆ false   ┆ 1.5       │
│ 2.0        ┆ 3.109375   ┆ 1.109375 ┆ 20        ┆ … ┆ 0.018028 ┆ 2          ┆ false   ┆ 2.5546875 │
└────────────┴────────────┴──────────┴───────────┴───┴──────────┴────────────┴─────────┴───────────┘

In [11]:
cum_df = ecdf_values_table(x).to_native()
cum_df

shape: (30, 5)
┌───────────┬─────────────┬─────────┬────────────────────────┬──────────────────────┐
│ position  ┆ granularity ┆ is_best ┆ cumulative_probability ┆ cumulative_frequency │
│ ---       ┆ ---         ┆ ---     ┆ ---                    ┆ ---                  │
│ f64       ┆ i32         ┆ bool    ┆ f64                    ┆ i64                  │
╞═══════════╪═════════════╪═════════╪════════════════════════╪══════════════════════╡
│ -2.953125 ┆ 0           ┆ false   ┆ 0.0                    ┆ 0                    │
│ 3.109375  ┆ 0           ┆ false   ┆ 1.0                    ┆ 1000                 │
│ -2.953125 ┆ 1           ┆ false   ┆ 0.0                    ┆ 0                    │
│ -2.0      ┆ 1           ┆ false   ┆ 0.026                  ┆ 26                   │
│ 2.0       ┆ 1           ┆ false   ┆ 0.98                   ┆ 980                  │
│ …         ┆ …           ┆ …       ┆ …                      ┆ …                    │
│ 0.5       ┆ 4           ┆ true    ┆ 0.695                  ┆ 695                  │
│ 1.25      ┆ 4           ┆ true    ┆ 0.892                  ┆ 892                  │
│ 1.75      ┆ 4           ┆ true    ┆ 0.964                  ┆ 964                  │
│ 2.0       ┆ 4           ┆ true    ┆ 0.98                   ┆ 980                  │
│ 3.109375  ┆ 4           ┆ true    ┆ 1.0                    ┆ 1000                 │
└───────────┴─────────────┴─────────┴────────────────────────┴──────────────────────┘

In [12]:
cum_df.filter(pl.col("granularity") == 0)

shape: (2, 5)
┌───────────┬─────────────┬─────────┬────────────────────────┬──────────────────────┐
│ position  ┆ granularity ┆ is_best ┆ cumulative_probability ┆ cumulative_frequency │
│ ---       ┆ ---         ┆ ---     ┆ ---                    ┆ ---                  │
│ f64       ┆ i32         ┆ bool    ┆ f64                    ┆ i64                  │
╞═══════════╪═════════════╪═════════╪════════════════════════╪══════════════════════╡
│ -2.953125 ┆ 0           ┆ false   ┆ 0.0                    ┆ 0                    │
│ 3.109375  ┆ 0           ┆ false   ┆ 1.0                    ┆ 1000                 │
└───────────┴─────────────┴─────────┴────────────────────────┴──────────────────────┘

In [13]:
ecdf_values_table([1.0, 2.0, 3.0, 4.0, 5.0], granularity="best").to_native()

pyarrow.Table
position: double
granularity: int32
is_best: bool
cumulative_probability: double
cumulative_frequency: int64
----
position: [[0.5,8]]
granularity: [[0,0]]
is_best: [[true,true]]
cumulative_probability: [[0,1]]
cumulative_frequency: [[0,5]]