In [14]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [15]:
import os

os.environ["KHISTO_BIN_DIR"] = (
    "/home/elouen/python/khisto-python/src/khiops/build/linux-gcc-debug/bin/khisto"
)
from khisto import histogram, histogram_series, histogram_bin_edges

In [16]:
import random
import numpy as np

x = np.array([random.gauss(0, 1) for _ in range(1000)])

In [17]:
histogram(x)

(array([0.00509091, 0.091     , 0.2736    , 0.36466667, 0.204     ,
        0.114     , 0.03066667, 0.00213333]),
 array([-3.625 , -2.25  , -2.25  , -1.25  , -1.25  , -0.625 , -0.625 ,
         0.875 ,  0.875 ,  1.375 ,  1.375 ,  1.875 ,  1.875 ,  2.625 ,
         2.625 ,  3.5625]))

In [18]:
import pyarrow as pa

x = pa.array([random.gauss(0, 1) for _ in range(1000)])
histogram(x)

(<pyarrow.lib.DoubleArray object at 0x768ffc1a8a60>
 [
   0.002666666667,
   0.064,
   0.2272,
   0.4,
   0.288,
   0.1133333333,
   0.04266666667,
   0.006222222222
 ],
 <pyarrow.lib.DoubleArray object at 0x768ffc1a85e0>
 [
   -3.4375,
   -2.3125,
   -2.3125,
   -1.4375,
   -1.4375,
   -0.8125,
   -0.8125,
   0.375,
   0.375,
   1.125,
   1.125,
   1.875,
   1.875,
   2.25,
   2.25,
   3.375
 ])

In [19]:
import jax

x = jax.numpy.array([random.gauss(0, 1) for _ in range(1000)])

In [20]:
histogram(x)

(Array([0.00391837, 0.0368    , 0.13866666, 0.248     , 0.35666665,
        0.175     , 0.052     , 0.00426667], dtype=float32),
 Array([-3.265625, -2.5     , -2.5     , -1.875   , -1.875   , -1.3125  ,
        -1.3125  , -0.6875  , -0.6875  ,  0.8125  ,  0.8125  ,  1.8125  ,
         1.8125  ,  2.3125  ,  2.3125  ,  3.484375], dtype=float32))

In [21]:
histogram(x.tolist())

([0.003918367347,
  0.0368,
  0.1386666667,
  0.248,
  0.3566666667,
  0.175,
  0.052,
  0.004266666667],
 [-3.265625,
  -2.5,
  -2.5,
  -1.875,
  -1.875,
  -1.3125,
  -1.3125,
  -0.6875,
  -0.6875,
  0.8125,
  0.8125,
  1.8125,
  1.8125,
  2.3125,
  2.3125,
  3.484375])

In [22]:
import pandas as pd

x = pd.Series([random.gauss(0, 1) for _ in range(1000)])
histogram(x)

(<pyarrow.lib.DoubleArray object at 0x768ffc1a9060>
 [
   0.01641025641,
   0.064,
   0.1614545455,
   0.2951111111,
   0.4373333333,
   0.2729411765,
   0.0576,
   0.009061946903
 ],
 <pyarrow.lib.DoubleArray object at 0x768ffc1a8b80>
 [
   -3.0390625,
   -2.125,
   -2.125,
   -1.6875,
   -1.6875,
   -1,
   -1,
   -0.4375,
   -0.4375,
   0.3125,
   0.3125,
   1.375,
   1.375,
   2.3125,
   2.3125,
   3.1953125
 ])

In [23]:
import polars as pl

x = pl.Series("x", [random.gauss(0, 1) for _ in range(1000)])
histogram(x)

(<pyarrow.lib.DoubleArray object at 0x768ffc1a8880>
 [
   0.01210810811,
   0.05653333333,
   0.2092307692,
   0.3854545455,
   0.192,
   0.03815384615,
   0.003636363636
 ],
 <pyarrow.lib.DoubleArray object at 0x768ffc1a9000>
 [
   -3.078125,
   -2.5,
   -2.5,
   -1.5625,
   -1.5625,
   -0.75,
   -0.75,
   0.625,
   0.625,
   1.6875,
   1.6875,
   2.5,
   2.5,
   3.875
 ])

In [24]:
histogram_bin_edges(x)

[-3.078125,
 -2.5,
 -2.5,
 -1.5625,
 -1.5625,
 -0.75,
 -0.75,
 0.625,
 0.625,
 1.6875,
 1.6875,
 2.5,
 2.5,
 3.875]

In [25]:
x = pd.Series([random.gauss(0, 1) for _ in range(1000)])

histogram_series(x).to_native()

,lower_bound,upper_bound,length,frequency,probability,density,granularity,is_best
0,-3.117188,-2.500000,0.617188,5,0.005,0.008101,4,False
1,-2.500000,-1.500000,1.000000,54,0.054,0.054000,4,False
2,-1.500000,-1.000000,0.500000,86,0.086,0.172000,4,False
3,-1.000000,0.000000,1.000000,307,0.307,0.307000,4,False
4,0.000000,0.500000,0.500000,219,0.219,0.438000,4,False
5,0.500000,1.000000,0.500000,162,0.162,0.324000,4,False
6,1.000000,1.500000,0.500000,96,0.096,0.192000,4,False
7,1.500000,2.000000,0.500000,46,0.046,0.092000,4,False
8,2.000000,2.500000,0.500000,18,0.018,0.036000,4,False
9,2.500000,3.289062,0.789062,7,0.007,0.008871,4,False
10,-3.117188,-1.812500,1.304688,29,0.029,0.022228,5,False
11,-1.812500,-1.312500,0.500000,50,0.050,0.100000,5,False
12,-1.312500,-0.687500,0.625000,153,0.153,0.244800,5,False
13,-0.687500,0.937500,1.625000,588,0.588,0.361846,5,False
14,0.937500,1.812500,0.875000,147,0.147,0.168000,5,False
15,1.812500,2.562500,0.750000,28,0.028,0.037333,5,False
16,2.562500,3.289062,0.726562,5,0.005,0.006882,5,False
17,-3.117188,3.289062,6.406250,1000,1.000,0.156098,1,False
18,-3.117188,-2.000000,1.117188,23,0.023,0.020587,2,False
19,-2.000000,0.000000,2.000000,429,0.429,0.214500,2,False
20,0.000000,2.000000,2.000000,523,0.523,0.261500,2,False
21,2.000000,3.289062,1.289062,25,0.025,0.019394,2,False
22,-3.117188,-2.000000,1.117188,23,0.023,0.020587,3,False
23,-2.000000,-1.000000,1.000000,122,0.122,0.122000,3,False
24,-1.000000,0.000000,1.000000,307,0.307,0.307000,3,False
25,0.000000,1.000000,1.000000,381,0.381,0.381000,3,False
26,1.000000,2.000000,1.000000,142,0.142,0.142000,3,False
27,2.000000,3.289062,1.289062,25,0.025,0.019394,3,False

In [26]:
x = pl.DataFrame({"x": [random.gauss(0, 1) for _ in range(1000)]})["x"]
x = pl.concat([x, pl.Series("y", [random.gauss(2, 1) for _ in range(1000)])])

histogram_series(x).to_native()

shape: (27, 8)
┌─────────────┬─────────────┬─────────┬───────────┬─────────────┬──────────┬─────────────┬─────────┐
│ lower_bound ┆ upper_bound ┆ length  ┆ frequency ┆ probability ┆ density  ┆ granularity ┆ is_best │
│ ---         ┆ ---         ┆ ---     ┆ ---       ┆ ---         ┆ ---      ┆ ---         ┆ ---     │
│ f64         ┆ f64         ┆ f64     ┆ i64       ┆ f64         ┆ f64      ┆ i32         ┆ bool    │
╞═════════════╪═════════════╪═════════╪═══════════╪═════════════╪══════════╪═════════════╪═════════╡
│ -3.0        ┆ -2.0        ┆ 1.0     ┆ 19        ┆ 0.0095      ┆ 0.0095   ┆ 4           ┆ false   │
│ -2.0        ┆ 0.0         ┆ 2.0     ┆ 502       ┆ 0.251       ┆ 0.1255   ┆ 4           ┆ false   │
│ 0.0         ┆ 2.0         ┆ 2.0     ┆ 947       ┆ 0.4735      ┆ 0.23675  ┆ 4           ┆ false   │
│ 2.0         ┆ 4.0         ┆ 2.0     ┆ 502       ┆ 0.251       ┆ 0.1255   ┆ 4           ┆ false   │
│ 4.0         ┆ 5.34375     ┆ 1.34375 ┆ 30        ┆ 0.015       ┆ 0.011163 ┆ 4           ┆ false   │
│ …           ┆ …           ┆ …       ┆ …         ┆ …           ┆ …        ┆ …           ┆ …       │
│ -3.0        ┆ 0.0         ┆ 3.0     ┆ 521       ┆ 0.2605      ┆ 0.086833 ┆ 2           ┆ false   │
│ 0.0         ┆ 5.34375     ┆ 5.34375 ┆ 1479      ┆ 0.7395      ┆ 0.138386 ┆ 2           ┆ false   │
│ -3.0        ┆ 0.0         ┆ 3.0     ┆ 521       ┆ 0.2605      ┆ 0.086833 ┆ 3           ┆ false   │
│ 0.0         ┆ 4.0         ┆ 4.0     ┆ 1449      ┆ 0.7245      ┆ 0.181125 ┆ 3           ┆ false   │
│ 4.0         ┆ 5.34375     ┆ 1.34375 ┆ 30        ┆ 0.015       ┆ 0.011163 ┆ 3           ┆ false   │
└─────────────┴─────────────┴─────────┴───────────┴─────────────┴──────────┴─────────────┴─────────┘