In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os

os.environ["KHISTO_BIN_DIR"] = (
    "/home/elouen/python/khisto-python/src/khiops/build/linux-gcc-debug/bin/khisto"
)
from khisto import histogram, histogram_series, histogram_bin_edges

In [3]:
import random
import numpy as np

x = np.array([random.gauss(0, 1) for _ in range(1000)])

In [4]:
histogram(x)

(array([0.01146269, 0.044     , 0.17333333, 0.35485714, 0.22      ,
        0.124     , 0.04533333, 0.00363121]),
 array([-3.0234375, -2.5      , -1.75     , -1.       ,  0.75     ,
         1.25     ,  1.75     ,  2.5      ,  3.6015625]))

In [5]:
import pyarrow as pa

x = pa.array([random.gauss(0, 1) for _ in range(1000)])
histogram(x, granularity="best", cumulative=True)

(<pyarrow.lib.DoubleArray object at 0x7d56de04e8c0>
 [
   0.002,
   0.026000000000000002,
   0.057,
   0.175,
   0.7190000000000001,
   0.8960000000000001,
   0.9780000000000001,
   0.9950000000000001,
   1
 ],
 <pyarrow.lib.DoubleArray object at 0x7d56de04e680>
 [
   -3.21875,
   -2.625,
   -1.875,
   -1.5,
   -0.875,
   0.625,
   1.25,
   1.875,
   2.25,
   3.203125
 ])

In [6]:
import jax

x = jax.numpy.array([random.gauss(0, 1) for _ in range(1000)])

INFO:2025-10-17 19:00:28,358:jax._src.xla_bridge:808: Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
INFO:jax._src.xla_bridge:Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
WARNING:2025-10-17 19:00:28,360:jax._src.xla_bridge:850: An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.
WARNING:jax._src.xla_bridge:An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

In [7]:
histogram(x)

(Array([0.01219048, 0.06933333, 0.216     , 0.356     , 0.156     ,
        0.068     , 0.01783607], dtype=float32),
 Array([-3.234375, -2.25    , -1.5     , -0.75    ,  1.      ,  1.75    ,
         2.      ,  2.953125], dtype=float32))

In [8]:
histogram(x.tolist())

([0.01219047619, 0.06933333333, 0.216, 0.356, 0.156, 0.068, 0.01783606557],
 [-3.234375, -2.25, -1.5, -0.75, 1.0, 1.75, 2.0, 2.953125])

In [9]:
import pandas as pd

x = pd.Series([random.gauss(0, 1) for _ in range(1000)])
histogram(x)

(<pyarrow.lib.DoubleArray object at 0x7d56d4470100>
 [
   0.01178947368,
   0.048,
   0.146,
   0.24,
   0.3451428571,
   0.184,
   0.08533333333,
   0.01107692308
 ],
 <pyarrow.lib.DoubleArray object at 0x7d56d4470220>
 [
   -3.4375,
   -2.25,
   -1.75,
   -1.25,
   -0.75,
   1,
   1.5,
   2.25,
   3.0625
 ])

In [10]:
import polars as pl

x = pl.Series("x", [random.gauss(0, 1) for _ in range(1000)])
histogram(x)

(<pyarrow.lib.DoubleArray object at 0x7d56a417c700>
 [
   0.016,
   0.07333333333,
   0.2306666667,
   0.3633333333,
   0.188,
   0.069,
   0.012
 ],
 <pyarrow.lib.DoubleArray object at 0x7d56a41133a0>
 [
   -2.75,
   -2.25,
   -1.5,
   -0.75,
   0.75,
   1.5,
   2.5,
   3.25
 ])

In [11]:
histogram_bin_edges(x)

[-2.75, -2.25, -1.5, -0.75, 0.75, 1.5, 2.5, 3.25]

In [12]:
x = pd.Series([random.gauss(0, 1) for _ in range(1000)])

histogram_series(x).to_native()

,lower_bound,upper_bound,length,frequency,probability,density,granularity,is_best
0,-3.015625,-2.0000,1.015625,23,0.023,0.022646,3,False
1,-2.000000,-1.5000,0.500000,46,0.046,0.092000,3,False
2,-1.500000,-1.0000,0.500000,82,0.082,0.164000,3,False
3,-1.000000,0.5000,1.500000,532,0.532,0.354667,3,False
4,0.500000,1.0000,0.500000,140,0.140,0.280000,3,False
5,1.000000,1.5000,0.500000,92,0.092,0.184000,3,False
6,1.500000,2.0000,0.500000,55,0.055,0.110000,3,False
7,2.000000,2.5000,0.500000,26,0.026,0.052000,3,False
8,2.500000,2.9375,0.437500,4,0.004,0.009143,3,False
9,-3.015625,-2.0000,1.015625,23,0.023,0.022646,4,False
10,-2.000000,-1.2500,0.750000,78,0.078,0.104000,4,False
11,-1.250000,-0.7500,0.500000,113,0.113,0.226000,4,False
12,-0.750000,0.5000,1.250000,469,0.469,0.375200,4,False
13,0.500000,1.2500,0.750000,193,0.193,0.257333,4,False
14,1.250000,2.0000,0.750000,94,0.094,0.125333,4,False
15,2.000000,2.5000,0.500000,26,0.026,0.052000,4,False
16,2.500000,2.9375,0.437500,4,0.004,0.009143,4,False
17,-3.015625,2.9375,5.953125,1000,1.000,0.167979,0,False
18,-3.015625,-1.8750,1.140625,29,0.029,0.025425,5,True
19,-1.875000,-1.2500,0.625000,72,0.072,0.115200,5,True
20,-1.250000,-0.7500,0.500000,113,0.113,0.226000,5,True
21,-0.750000,0.3750,1.125000,434,0.434,0.385778,5,True
22,0.375000,1.3750,1.000000,255,0.255,0.255000,5,True
23,1.375000,1.8750,0.500000,57,0.057,0.114000,5,True
24,1.875000,2.5000,0.625000,36,0.036,0.057600,5,True
25,2.500000,2.9375,0.437500,4,0.004,0.009143,5,True
26,-3.015625,-2.0000,1.015625,23,0.023,0.022646,1,False
27,-2.000000,2.0000,4.000000,947,0.947,0.236750,1,False
28,2.000000,2.9375,0.937500,30,0.030,0.032000,1,False
29,-3.015625,-2.0000,1.015625,23,0.023,0.022646,2,False
30,-2.000000,-1.0000,1.000000,128,0.128,0.128000,2,False
31,-1.000000,1.0000,2.000000,672,0.672,0.336000,2,False
32,1.000000,2.0000,1.000000,147,0.147,0.147000,2,False
33,2.000000,2.9375,0.937500,30,0.030,0.032000,2,False

In [13]:
x = pl.DataFrame({"x": [random.gauss(0, 1) for _ in range(1000)]})["x"]
x = pl.concat([x, pl.Series("y", [random.gauss(2, 1) for _ in range(1000)])])

histogram_series(x, cumulative=True).to_native()

shape: (58, 9)
┌────────────┬────────────┬───────────┬───────────┬───┬──────────┬───────────┬─────────┬───────────┐
│ lower_boun ┆ upper_boun ┆ length    ┆ frequency ┆ … ┆ density  ┆ granulari ┆ is_best ┆ cumulativ │
│ d          ┆ d          ┆ ---       ┆ ---       ┆   ┆ ---      ┆ ty        ┆ ---     ┆ e_probabi │
│ ---        ┆ ---        ┆ f64       ┆ i64       ┆   ┆ f64      ┆ ---       ┆ bool    ┆ lity      │
│ f64        ┆ f64        ┆           ┆           ┆   ┆          ┆ i32       ┆         ┆ ---       │
│            ┆            ┆           ┆           ┆   ┆          ┆           ┆         ┆ f64       │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═════════╪═══════════╡
│ -3.460938  ┆ -2.0       ┆ 1.4609375 ┆ 17        ┆ … ┆ 0.005818 ┆ 3         ┆ false   ┆ 0.0085    │
│ -2.0       ┆ 0.0        ┆ 2.0       ┆ 511       ┆ … ┆ 0.12775  ┆ 3         ┆ false   ┆ 0.264     │
│ 0.0        ┆ 2.0        ┆ 2.0       ┆ 930       ┆ … ┆ 0.2325   ┆ 3         ┆ false   ┆ 0.729     │
│ 2.0        ┆ 4.0        ┆ 2.0       ┆ 522       ┆ … ┆ 0.1305   ┆ 3         ┆ false   ┆ 0.99      │
│ 4.0        ┆ 5.8359375  ┆ 1.8359375 ┆ 20        ┆ … ┆ 0.005447 ┆ 3         ┆ false   ┆ 1.0       │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …       ┆ …         │
│ -3.460938  ┆ 0.0        ┆ 3.4609375 ┆ 528       ┆ … ┆ 0.07628  ┆ 1         ┆ false   ┆ 0.264     │
│ 0.0        ┆ 5.8359375  ┆ 5.8359375 ┆ 1472      ┆ … ┆ 0.126115 ┆ 1         ┆ false   ┆ 1.0       │
│ -3.460938  ┆ 0.0        ┆ 3.4609375 ┆ 528       ┆ … ┆ 0.07628  ┆ 2         ┆ false   ┆ 0.264     │
│ 0.0        ┆ 4.0        ┆ 4.0       ┆ 1452      ┆ … ┆ 0.1815   ┆ 2         ┆ false   ┆ 0.99      │
│ 4.0        ┆ 5.8359375  ┆ 1.8359375 ┆ 20        ┆ … ┆ 0.005447 ┆ 2         ┆ false   ┆ 1.0       │
└────────────┴────────────┴───────────┴───────────┴───┴──────────┴───────────┴─────────┴───────────┘