In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os

os.environ["KHISTO_BIN_DIR"] = (
    "/home/elouen/python/khisto-python/src/khiops/build/linux-gcc-debug/bin/khisto"
)
from khisto import histogram, histogram_series, histogram_bin_edges

In [3]:
import random
import numpy as np

x = np.array([random.gauss(0, 1) for _ in range(1000)])

In [4]:
histogram(x)

(array([0.00778378, 0.0512    , 0.1376    , 0.27      , 0.3808    ,
        0.29      , 0.14666667, 0.0736    , 0.01896296]),
 array([-3.53125, -2.375  , -1.75   , -1.125  , -0.625  ,  0.625  ,
         1.125  ,  1.5    ,  2.125  ,  2.96875]))

In [5]:
import pyarrow as pa

x = pa.array([random.gauss(0, 1) for _ in range(1000)])
histogram(x, granularity="best", cumulative=True)

(<pyarrow.lib.DoubleArray object at 0x72f578582740>
 [
   0,
   0.009,
   0.053,
   0.191,
   0.8500000000000001,
   0.9600000000000001,
   0.9950000000000001,
   1
 ],
 <pyarrow.lib.DoubleArray object at 0x72f5785827a0>
 [
   -2.875,
   -2.25,
   -1.625,
   -0.875,
   1.125,
   1.875,
   2.5,
   3.25
 ])

In [6]:
x = np.array([random.gauss(0, 1) for _ in range(1000)])

histogram_series(x, cumulative=True)

┌───────────────────────────────────────┐
|          Narwhals DataFrame           |
| Use `.to_native` to see native output |
└───────────────────────────────────────┘

In [7]:
import jax

x = jax.numpy.array([random.gauss(0, 1) for _ in range(1000)])

INFO:2025-10-20 10:25:22,165:jax._src.xla_bridge:808: Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
INFO:jax._src.xla_bridge:Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
WARNING:2025-10-20 10:25:22,167:jax._src.xla_bridge:850: An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.
WARNING:jax._src.xla_bridge:An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

In [8]:
histogram(x)

(Array([0.012288  , 0.054     , 0.13      , 0.286     , 0.424     ,
        0.234     , 0.064     , 0.01406593], dtype=float32),
 Array([-3.2265625, -2.25     , -1.75     , -1.25     , -0.25     ,
         0.5      ,  1.5      ,  2.25     ,  2.9609375], dtype=float32))

In [9]:
histogram(x.tolist())

([0.012288, 0.054, 0.13, 0.286, 0.424, 0.234, 0.064, 0.01406593407],
 [-3.2265625, -2.25, -1.75, -1.25, -0.25, 0.5, 1.5, 2.25, 2.9609375])

In [10]:
import pandas as pd

x = pd.Series([random.gauss(0, 1) for _ in range(1000)])
histogram(x)

(<pyarrow.lib.DoubleArray object at 0x72f55a985ae0>
 [
   0.00769924812,
   0.04,
   0.138,
   0.287,
   0.38,
   0.2106666667,
   0.094,
   0.03402531646
 ],
 <pyarrow.lib.DoubleArray object at 0x72f55a985a80>
 [
   -3.5390625,
   -2.5,
   -1.75,
   -1.25,
   -0.25,
   0.75,
   1.5,
   2,
   2.6171875
 ])

In [11]:
import polars as pl

x = pl.Series("x", [random.gauss(0, 1) for _ in range(1000)])
histogram(x)

(<pyarrow.lib.DoubleArray object at 0x72f50c171b40>
 [
   0.01252173913,
   0.07563636364,
   0.1818181818,
   0.3686666667,
   0.2501818182,
   0.08213333333,
   0.009365853659
 ],
 <pyarrow.lib.DoubleArray object at 0x72f50c171960>
 [
   -2.96875,
   -2.25,
   -1.5625,
   -0.875,
   0.625,
   1.3125,
   2.25,
   3.53125
 ])

In [12]:
histogram_bin_edges(x)

[-2.96875, -2.25, -1.5625, -0.875, 0.625, 1.3125, 2.25, 3.53125]

In [13]:
x = pd.Series([random.gauss(0, 1) for _ in range(1000)])

histogram_series(x).to_native()

,lower_bound,upper_bound,length,frequency,probability,density,granularity,is_best
0,-3.3125,-2.5000,0.8125,5,0.005,0.006154,3,False
1,-2.5000,-2.0000,0.5000,17,0.017,0.034000,3,False
2,-2.0000,-1.5000,0.5000,49,0.049,0.098000,3,False
3,-1.5000,-1.0000,0.5000,91,0.091,0.182000,3,False
4,-1.0000,-0.5000,0.5000,155,0.155,0.310000,3,False
5,-0.5000,0.5000,1.0000,394,0.394,0.394000,3,False
6,0.5000,1.0000,0.5000,142,0.142,0.284000,3,False
7,1.0000,1.5000,0.5000,81,0.081,0.162000,3,False
8,1.5000,2.0000,0.5000,49,0.049,0.098000,3,False
9,2.0000,3.0000,1.0000,17,0.017,0.017000,3,False
10,-3.3125,-2.3125,1.0000,8,0.008,0.008000,4,False
11,-2.3125,-1.6875,0.6250,38,0.038,0.060800,4,False
12,-1.6875,-0.8125,0.8750,161,0.161,0.184000,4,False
13,-0.8125,0.8125,1.6250,606,0.606,0.372923,4,False
14,0.8125,1.9375,1.1250,169,0.169,0.150222,4,False
15,1.9375,3.0000,1.0625,18,0.018,0.016941,4,False
16,-3.3125,3.0000,6.3125,1000,1.000,0.158416,0,False
17,-3.3125,-2.0000,1.3125,22,0.022,0.016762,1,False
18,-2.0000,2.0000,4.0000,961,0.961,0.240250,1,False
19,2.0000,3.0000,1.0000,17,0.017,0.017000,1,False
20,-3.3125,-2.0000,1.3125,22,0.022,0.016762,2,False
21,-2.0000,-1.0000,1.0000,140,0.140,0.140000,2,False
22,-1.0000,1.0000,2.0000,691,0.691,0.345500,2,False
23,1.0000,2.0000,1.0000,130,0.130,0.130000,2,False
24,2.0000,3.0000,1.0000,17,0.017,0.017000,2,False

In [14]:
x = pl.DataFrame({"x": [random.gauss(0, 1) for _ in range(1000)]})["x"]
x = pl.concat([x, pl.Series("y", [random.gauss(2, 1) for _ in range(1000)])])

histogram_series(x, cumulative=True).to_native()

shape: (41, 9)
┌────────────┬────────────┬──────────┬───────────┬───┬──────────┬────────────┬─────────┬───────────┐
│ lower_boun ┆ upper_boun ┆ length   ┆ frequency ┆ … ┆ density  ┆ granularit ┆ is_best ┆ cumulativ │
│ d          ┆ d          ┆ ---      ┆ ---       ┆   ┆ ---      ┆ y          ┆ ---     ┆ e_probabi │
│ ---        ┆ ---        ┆ f64      ┆ i64       ┆   ┆ f64      ┆ ---        ┆ bool    ┆ lity      │
│ f64        ┆ f64        ┆          ┆           ┆   ┆          ┆ i32        ┆         ┆ ---       │
│            ┆            ┆          ┆           ┆   ┆          ┆            ┆         ┆ f64       │
╞════════════╪════════════╪══════════╪═══════════╪═══╪══════════╪════════════╪═════════╪═══════════╡
│ -4.296875  ┆ 6.296875   ┆ 10.59375 ┆ 2000      ┆ … ┆ 0.094395 ┆ 0          ┆ false   ┆ 1.0       │
│ -4.296875  ┆ 0.0        ┆ 4.296875 ┆ 506       ┆ … ┆ 0.05888  ┆ 1          ┆ false   ┆ 0.253     │
│ 0.0        ┆ 6.296875   ┆ 6.296875 ┆ 1494      ┆ … ┆ 0.11863  ┆ 1          ┆ false   ┆ 1.0       │
│ -4.296875  ┆ -4.0       ┆ 0.296875 ┆ 1         ┆ … ┆ 0.001684 ┆ 2          ┆ false   ┆ 0.0005    │
│ -4.0       ┆ 0.0        ┆ 4.0      ┆ 505       ┆ … ┆ 0.063125 ┆ 2          ┆ false   ┆ 0.253     │
│ …          ┆ …          ┆ …        ┆ …         ┆ … ┆ …        ┆ …          ┆ …       ┆ …         │
│ 0.0        ┆ 2.5        ┆ 2.5      ┆ 1184      ┆ … ┆ 0.2368   ┆ 6          ┆ false   ┆ 0.845     │
│ 2.5        ┆ 3.0        ┆ 0.5      ┆ 159       ┆ … ┆ 0.159    ┆ 6          ┆ false   ┆ 0.9245    │
│ 3.0        ┆ 3.75       ┆ 0.75     ┆ 114       ┆ … ┆ 0.076    ┆ 6          ┆ false   ┆ 0.9815    │
│ 3.75       ┆ 4.5        ┆ 0.75     ┆ 30        ┆ … ┆ 0.02     ┆ 6          ┆ false   ┆ 0.9965    │
│ 4.5        ┆ 6.296875   ┆ 1.796875 ┆ 7         ┆ … ┆ 0.001948 ┆ 6          ┆ false   ┆ 1.0       │
└────────────┴────────────┴──────────┴───────────┴───┴──────────┴────────────┴─────────┴───────────┘